/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "allocator.h"

void case_1()
{
	allocator_init();
	void *a1 = allocator_allocate(2);
	void *a2 = allocator_allocate(3);
	void *a3 = allocator_allocate(4);
	allocator_free(a2);
	allocator_free(a1);
	allocator_allocate(1);
}

void case_2()
{
	allocator_init();
	void *a1 = allocator_allocate(2);
	void *a2 = allocator_allocate(3);
	void *a3 = allocator_allocate(4);
	allocator_free(a2);
	allocator_free(a3);
	allocator_allocate(1);
}

void case_3()
{
	allocator_init();
	void *a1 = allocator_allocate(2);
	void *a2 = allocator_allocate(3);
	void *a3 = allocator_allocate(4);
	allocator_free(a1);
	allocator_free(a3);
	allocator_free(a2);
	allocator_allocate(1);
}

int main(void)
{
	case_1();
	case_2();
	case_3();
    /* Loop forever */
	for(;;);
}

